/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorr;

/**
 *
 * @author ASUS
 */
public class framekalkulatorr extends javax.swing.JFrame {

    /**
     * Creates new form framekalkulatorr
     */
    double a,b,c,d,e,f,g,h,pph,bea_hasil,ppn_hasil,pph_hasil,total,cbm_hasil,fix;
    public framekalkulatorr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_harga_barang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_kurs = new javax.swing.JTextField();
        txt_vcbm = new javax.swing.JTextField();
        txt_cbm = new javax.swing.JTextField();
        txt_kirim = new javax.swing.JTextField();
        cb_bea = new javax.swing.JComboBox<>();
        cb_ppn = new javax.swing.JComboBox<>();
        txt_pph = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jml_bea = new javax.swing.JTextField();
        jml_ppn = new javax.swing.JTextField();
        jml_pph = new javax.swing.JTextField();
        jml_total = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jml_cbm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KALKULATOR BEA MASUK DAN PAJAK IMPOR");

        jLabel2.setText("PT LAKSA TECHNO");

        jLabel3.setText("HARGA BARANG");

        jLabel4.setText("KURS KE RUPIAH");

        jLabel5.setText("TARIF BEA MASUK (%)");

        jLabel6.setText("TARIF PPN (%)");

        jLabel7.setText("TARIF PPH (%)");

        jLabel8.setText("TARIF CBM");

        jLabel9.setText("BIAYA KIRIM");

        txt_harga_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harga_barangActionPerformed(evt);
            }
        });

        jLabel10.setText("VOLUME BIAYA CBM");

        txt_kurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kursActionPerformed(evt);
            }
        });

        txt_vcbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vcbmActionPerformed(evt);
            }
        });

        txt_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kirimActionPerformed(evt);
            }
        });

        cb_bea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 %", "5 %", "7.5 %", "10 %", "12.5 %", "15 %", "20 %", "25 %" }));
        cb_bea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_beaActionPerformed(evt);
            }
        });

        cb_ppn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 %", "5 %", "7.5 %", "11 %" }));
        cb_ppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ppnActionPerformed(evt);
            }
        });

        txt_pph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pphActionPerformed(evt);
            }
        });

        jLabel11.setText("JUMLAH BEA MASUK (RP)");

        jLabel12.setText("JUMLAH PPN (RP)");

        jLabel13.setText("JUMLAH PPH (RP)");

        jLabel14.setText("JUMLAH HITUNG CBM");

        jLabel15.setText("JUMLAH TOTAL");

        jml_bea.setEditable(false);
        jml_bea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_beaActionPerformed(evt);
            }
        });

        jml_ppn.setEditable(false);
        jml_ppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_ppnActionPerformed(evt);
            }
        });

        jml_pph.setEditable(false);

        jml_total.setEditable(false);

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_reset.setText("Bersihkan");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jml_cbm.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(346, 346, 346))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_harga_barang)
                    .addComponent(txt_kurs)
                    .addComponent(txt_vcbm)
                    .addComponent(txt_cbm)
                    .addComponent(txt_kirim)
                    .addComponent(cb_bea, 0, 120, Short.MAX_VALUE)
                    .addComponent(cb_ppn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_pph))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jml_bea)
                            .addComponent(jml_ppn)
                            .addComponent(jml_pph)
                            .addComponent(jml_cbm, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jml_total)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(btn_hitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_harga_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jml_bea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_kurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jml_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_bea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jml_pph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jml_cbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_pph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jml_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_vcbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_cbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jml_ppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_ppnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_ppnActionPerformed

    private void cb_beaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_beaActionPerformed
        // TODO add your handling code here:
        String pil_bea = (String)cb_bea.getSelectedItem();
        if (pil_bea == "0 %"){
            c = 0;
        }else if(pil_bea == "5 %"){
            c = 0.05;
        }else if(pil_bea == "7.5 %"){
            c = 0.075;
        }else if(pil_bea == "10 %"){
            c = 0.1;
        }else if(pil_bea == "12.5 %"){
            c = 0.125;
        }else if(pil_bea == "15 %"){
            c = 0.15;
        }else if(pil_bea == "20 %"){
            c = 0.2;
        }else if(pil_bea == "25 %"){
            c = 0.25;
        }
    }//GEN-LAST:event_cb_beaActionPerformed

    private void cb_ppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ppnActionPerformed
        // TODO add your handling code here:
        String pil_ppn = (String)cb_ppn.getSelectedItem();
        if(pil_ppn == "0 %"){
            d = 0;
        }else if(pil_ppn == "5 %"){
            d = 0.05;
        }else if(pil_ppn == "7.5 %"){
            d = 0.075;
        }else if(pil_ppn == "11 %"){
            d = 0.11;
        }
    }//GEN-LAST:event_cb_ppnActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(this.txt_harga_barang.getText());
        b = Double.parseDouble(this.txt_kurs.getText());
        h = Double.parseDouble(this.txt_kirim.getText());
        e= Double.parseDouble(this.txt_pph.getText());
        f= Double.parseDouble(this.txt_vcbm.getText());
        g = Double.parseDouble(this.txt_cbm.getText());
        //Aritmatika Perhitungan
        bea_hasil = (((a*b)*c)); // ((a*b)*c
        ppn_hasil = (((a*b)*d));
        pph_hasil = (bea_hasil*(e/100));
	Double hsl_cbm = f*g;
        total = bea_hasil+ppn_hasil+pph_hasil+hsl_cbm+h;
        
        //Menampilkan output pada textfield yang akan disediakan
        this.jml_bea.setText(""+Math.round(bea_hasil));
        this.jml_ppn.setText(""+Math.round(ppn_hasil));
        this.jml_pph.setText(""+Math.round(pph_hasil));
        this.jml_cbm.setText(""+Math.round(hsl_cbm));
        this.jml_total.setText(""+Math.round(total));
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txt_harga_barang.setText("");
        txt_kurs.setText("");
        txt_pph.setText("");
        txt_vcbm.setText("");
        txt_cbm.setText("");
        txt_kirim.setText("");
        jml_bea.setText("");
        jml_ppn.setText("");
        jml_pph.setText("");
        jml_total.setText("");
        jml_cbm.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_vcbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vcbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vcbmActionPerformed

    private void txt_harga_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harga_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harga_barangActionPerformed

    private void txt_kursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kursActionPerformed

    private void txt_pphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pphActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_pphActionPerformed

    private void jml_beaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_beaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_beaActionPerformed

    private void txt_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kirimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framekalkulatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framekalkulatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framekalkulatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framekalkulatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framekalkulatorr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cb_bea;
    private javax.swing.JComboBox<String> cb_ppn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jml_bea;
    private javax.swing.JTextField jml_cbm;
    private javax.swing.JTextField jml_pph;
    private javax.swing.JTextField jml_ppn;
    private javax.swing.JTextField jml_total;
    private javax.swing.JTextField txt_cbm;
    private javax.swing.JTextField txt_harga_barang;
    private javax.swing.JTextField txt_kirim;
    private javax.swing.JTextField txt_kurs;
    private javax.swing.JTextField txt_pph;
    private javax.swing.JTextField txt_vcbm;
    // End of variables declaration//GEN-END:variables
}
